apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jeferson
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: SQS_ENDPOINT
          value: TBD
        - name: S3_ENDPOINT
          value: TBD
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: jeferson
  name: nginx-service
spec:
  type: LoadBalance
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80